name: cresenity
description: Cresenity Framework
version: 0.0.1
author: ITTRON Global Technology
homepage: cresenity.com

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^2.0.4
  toast: ^0.1.5
  shared_preferences: ^0.5.6+1
  equatable: ^0.5.1
  http: ^0.12.0+4
  flushbar: ^1.9.1
  url_launcher: ^5.2.3
  intl: ^0.16.1
  flutter_bloc: ^0.21.0
  bloc: ^0.15.0
  dio: ^3.0.9
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
   - assets/img/double_ring_loading_io.gif

  fonts:
    - family: MaterialIcons
      fonts:
        - asset: assets/fonts/icons/MaterialIcons.ttf

    - family: FontAwesomeIcons
      fonts:
        - asset: assets/fonts/icons/FontAwesomeIcons.ttf
